import { access, cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { run, runPnpm } from './process.mjs';

export const DEFAULT_COMPILERS = [
  {
    alias: 'typescript-5',
    label: '5.8.3',
    specifier: 'npm:typescript@5.8.3',
  },
  {
    alias: 'typescript-6',
    label: '6.0.2',
    specifier: 'npm:@typescript/typescript6@6.0.2',
  },
  {
    alias: 'typescript-7',
    label: '7.0.2',
    specifier: 'npm:typescript@7.0.2',
  },
];

export const createAllExportsSource = packages => {
  const specifiers = packages.flatMap(workspacePackage =>
    workspacePackage.exportSpecifiers.map(specifier => ({
      packageName: workspacePackage.packageJson.name,
      specifier,
    })),
  );
  const lines = [
    '// Generated by tools/typescript-compatibility.',
    `// ${packages.length} packages and ${specifiers.length} exported subpaths.`,
    '',
  ];

  for (const [index, { packageName, specifier }] of specifiers.entries()) {
    lines.push(`// ${packageName}`);
    lines.push(`type PackageExport${index} = typeof import(${JSON.stringify(specifier)});`);
  }

  lines.push('', 'export {};', '');
  return lines.join('\n');
};

export const createCompilerOptions = ({ moduleResolution, skipLibCheck }) => ({
  allowSyntheticDefaultImports: true,
  lib: ['ES2022', 'DOM', 'DOM.Iterable'],
  module: moduleResolution === 'Bundler' ? 'ESNext' : 'NodeNext',
  moduleResolution,
  noEmit: true,
  resolveJsonModule: true,
  skipLibCheck,
  strict: true,
  target: 'ES2022',
  types: ['node'],
});

const writeConsumer = async ({
  consumerDir,
  fixtureFile,
  packageManager,
  packages,
  compilers,
}) => {
  await mkdir(consumerDir, { recursive: true });
  const packageJson = {
    name: 'ai-sdk-typescript-compatibility-consumer',
    packageManager,
    private: true,
    type: 'module',
    dependencies: Object.fromEntries(
      packages.map(workspacePackage => [
        workspacePackage.packageJson.name,
        `file:${workspacePackage.tarball}`,
      ]),
    ),
    devDependencies: {
      '@types/json-schema': '7.0.15',
      '@types/node': '22.19.19',
      '@types/react': '18.3.28',
      '@types/react-dom': '18.3.7',
      ...Object.fromEntries(
        compilers
          .filter(compiler => compiler.alias != null)
          .map(compiler => [compiler.alias, compiler.specifier]),
      ),
    },
    pnpm: {
      onlyBuiltDependencies: ['esbuild'],
      overrides: Object.fromEntries(
        packages.map(workspacePackage => [
          workspacePackage.packageJson.name,
          `file:${workspacePackage.tarball}`,
        ]),
      ),
    },
  };

  await writeFile(
    path.join(consumerDir, 'package.json'),
    `${JSON.stringify(packageJson, null, 2)}\n`,
  );
  await writeFile(
    path.join(consumerDir, 'all-exports.ts'),
    createAllExportsSource(packages),
  );
  await cp(fixtureFile, path.join(consumerDir, 'representative-api.ts'));

  const tiers = [
    {
      files: ['all-exports.ts'],
      name: 'all-exports',
      skipLibCheck: true,
    },
    {
      files: ['representative-api.ts'],
      name: 'representative',
      skipLibCheck: false,
    },
  ];

  for (const resolution of ['Bundler', 'NodeNext']) {
    for (const tier of tiers) {
      await writeFile(
        path.join(
          consumerDir,
          `tsconfig.${tier.name}.${resolution.toLowerCase()}.json`,
        ),
        `${JSON.stringify(
          {
            compilerOptions: createCompilerOptions({
              moduleResolution: resolution,
              skipLibCheck: tier.skipLibCheck,
            }),
            files: tier.files,
          },
          null,
          2,
        )}\n`,
      );
    }
  }
};

const resolveAliasCompiler = async (consumerDir, compiler) => {
  const packageDirectory = path.join(consumerDir, 'node_modules', compiler.alias);
  const packageJson = JSON.parse(
    await readFile(path.join(packageDirectory, 'package.json'), 'utf8'),
  );
  const bins =
    typeof packageJson.bin === 'string'
      ? { tsc: packageJson.bin }
      : packageJson.bin;
  const relative = bins?.tsc ?? bins?.tsc6 ?? Object.values(bins ?? {})[0];

  if (relative == null) {
    throw new Error(`${compiler.alias} does not expose a compiler binary.`);
  }

  const executable = path.join(packageDirectory, relative);
  await access(executable);
  return executable;
};

export const checkPackedPackages = async ({
  compilers,
  consumerDir,
  fixtureFile,
  packageManager,
  packages,
}) => {
  await writeConsumer({
    consumerDir,
    fixtureFile,
    packageManager,
    packages,
    compilers,
  });
  await runPnpm(['install', '--no-frozen-lockfile'], {
    capture: true,
    cwd: consumerDir,
    env: {
      ...process.env,
      INIT_CWD: consumerDir,
      PWD: consumerDir,
    },
  });

  for (const compiler of compilers) {
    const executable =
      compiler.executable ?? (await resolveAliasCompiler(consumerDir, compiler));
    const version = await run(executable, ['--version'], {
      capture: true,
      cwd: consumerDir,
    });
    const actualVersion = version.stdout.trim() || version.stderr.trim();
    if (!actualVersion.includes(compiler.label)) {
      throw new Error(
        `Compiler ${executable} reported ${actualVersion}; expected ${compiler.label}.`,
      );
    }
    process.stdout.write(`Checking TypeScript ${compiler.label} (${actualVersion})\n`);

    for (const resolution of ['bundler', 'nodenext']) {
      for (const tier of ['all-exports', 'representative']) {
        process.stdout.write(`  ${resolution} / ${tier}\n`);
        await run(
          executable,
          [
            '--project',
            `tsconfig.${tier}.${resolution}.json`,
            '--pretty',
            'false',
          ],
          { cwd: consumerDir },
        );
      }
    }
  }
};
